# Generated by Django 6.0.3 on 2026-03-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='student@email.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
